let list1 = [
    ["Y a t il un prix nobel de mathématiques ?","Nobel",""],
    ["218/2=119","119",""],
    ["En anglais l’antonyme de wet est dry ?","dry","OUI"],
    ["La femelle du lièvre est la hase ?","hase","OUI"],
    ["En anglais near veut dire près ?","près","OUI"],
    ["21*5=115 ?","115",""],
    ["La capitale de la GRANDE BRETAGNE est Londres ?","Londres","OUI"],
    ["La capitale du COSTA RICA est Santiago ?","Santiago",""],
    ["L’antonyme de ignominie est honte ?","honte",""],
    ["En anglais always veut dire toujours ?","toujours","OUI"],
    ["La capitale de la CHINE est Pékin ?","Pékin","OUI"],
    ["L’homonyme de dialecte est patois ?","patois","OUI"],
    ["En anglais need veut dire besoin ?","besoin","OUI"],
    ["La traduction de to eat en français est manger ?","manger","OUI"],
    ["en anglais currency veut dire courant ?","currency",""],
    ["En anglais drink veut dire boire ?","boire","OUI"],
    ["La capitale de la COTE D’IVOIRE est Abidjan ?","Abidjan",""],
    ["8 x 8=64 ?","64","OUI"],
    ["on dit un aéroport ?","un","OUI"],
    ["En anglais Pick up est le contraire de hang up ?","hang up","OUI"],
    ["La vache meugle ?","meugle","OUI"],
    ["en anglais above  veut dire  au dessus  ?","Au dessus","OUI"],
    ["La capitale du DANEMARK est Stockholm ?","Stockholm",""],
    ["en anglais far veut dire loin ?","loin","OUI"],
    ["La capitale de l’ALLEMAGNE est Berlin ?","Berlin","OUI"],
    ["on dit une aérogare ?","une","OUI"],
    ["9*9=81 ?","81","OUI"],
    ["500-400=200 ?","200",""],
    ["200-99=101 ?","101","OUI"],
    ["Le drapeau américain a 49 étoiles ?","49 étoiles",""],
    ["La pie chante ?","chante",""],
    ["L’antonyme de vide est plein ?","plein","OUI"],
    ["8X5=40 ?","40","OUI"],
    ["Le corbeau croasse ?","croasse","OUI"],
    ["En anglais can veut dire pouvoir ?","pouvoir","OUI"],
    ["416/4=114 ?","114",""],
    ["214/2=107","107","OUI"],
    ["La capitale de la RUSSIE est Moscou ?","Moscou","OUI"],
    ["La capitale de l’AUSTRALIE est Canberra ?","Canberra ","OUI"],
    ["1 quintal équivaut à 100 kg ?","100 kg","OUI"],
    ["La capitale du Brésil est Rio ?","Rio",""],
    ["on écrit j’appelle avec deux l ?","j’appelle","OUI"],
    ["homonyme d’ ubuesque est ridicule ?","ridicule","OUI"],
    ["5 % de 40 = 2 ?","2","OUI"],
    ["En anglais eat veut dire manger ?","manger","OUI"],
    ["309/3=103 ?","103","OUI"],
    ["324/3=118 ?","118",""],
    ["La capitale du NIGERIA est Lagos ?","Lagos",""],
    ["Le drapeau japonais est blanc et rouge ?","blanc rouge","OUI"],
    ["150-48=102 ?","102","OUI"],
    ["La capitale du CHILI est San José ?","San José",""],
    ["6*6=36 ?","36","OUI"],
    ["La capitale de la COLOMBIE est Bogota ?","Bogota","OUI"],
    ["La grenouille croasse ?","croasse",""],
    ["7*7=42 ?","42",""],
    ["en anglais since veut dire depuis ?","depuis","OUI"],
    ["20*5%=1, ?","1","OUI"],
    ["En anglais survey veut dire survivre ?","survivre",""],
    ["En anglais if veut dire si ?","si","OUI"],
    ["La capitale de la Suède est Copenhague ?","Copenhague",""],
    ["l’antonyme de notoriété est anonymat ?","anonymat","OUI"],
    ["1000 litres font 1m3 ?","1m3","OUI"],
    ["424/4=106 ?","106","OUI"],
    ["La capitale de l’ESPAGNE est Madrid ?","Madrid","OUI"]
  ]

  let list2 = [
    ["Fourbe est synonyme de perfide ?","perfide","OUI"],
    ["HOLLYWOOD est situé en Floride ?","Floride",""],
    ["à l’instar de se traduit par comme ?","comme","OUI"],
    ["Date de la 1ère crise pétrolière est 1973 ?","1973","OUI"],
    ["Le parc de YELLOWSTONE est dans le Wyoming ?","WYOMING","OUI"],
    ["200-113=87 ?","87","OUI"],
    ["L’auteur de 1984 est J. Steinbeck ?","J. Steinbeck",""],
    ["Prérogative signifie avantage ?","avantage","OUI"],
    ["Une rouste est une torgnole ?","torgnole","OUI"],
    ["En anglais occupé se dit busy ?","Busy ","OUI"],
    ["Création Organisation des Nations Unies juin 1945 ?","Juin 1945","OUI"],
    ["Le code départemental de la Savoie est 74 ?","74",""],
    ["Le parc d’Ordesa est au Portugal ?","Portugal",""],
    ["OCEAN PARK est à Hong Kong ?","HONG KONG","OUI"],
    ["La date de la Révolution française est 1889?","1889",""],
    ["Le code départemental de la Haute saöne est 71 ?","71",""],
    ["Le code départemental des Yvelines est 78 ?","78","OUI"],
    ["44*2=92 ?","92",""],
    ["46*2=88 ?","88",""],
    ["Corneille a écrit Le Cid ?","Corneille","OUI"],
    ["téméraire est synonyme d’ambitieux ?","ambitieux","OUI"],
    ["Election de Barack OBAMA en 2008 ?","2008","OUI"],
    ["Le code départemental de la Sarthe est 72 ?","72","OUI"],
    ["200-107=93 ?","93","OUI"],
    ["L’auteur de Ulysse est James Joyce ?","J. Joyce","OUI"],
    ["le synonyme de vicissitudes est aléa ? ","Aléa","OUI"],
    ["En anglais santé se dit wealth ?","Wealth",""],
    ["Les femmes votent au suffrage universel en 1945 ?","1945",""],
    ["Le code départemental des Deux sèvres est 76 ?","76",""],
    ["En anglais objectif se dit goal ?","goal","OUI"],
    ["Le code départemental de la Saöne et loire est 70 ?","70",""],
    ["Le code départemental de la Seine et marne est 77 ?","77","OUI"],
    ["L’auteur de Roméo et Juliette est W. Shakespeare ?","W. Shakespeare","OUI"],
    ["L’ ACROPOLE est en Italie ?","Italie",""],
    ["Grèves et manifestations en France en mars 1968 ?","Mars 1968",""],
    ["172/2=85 ?","85",""],
    ["100-9=91 ?","91","OUI"],
    ["Date du 1 er krach boursier est 1930 ?","1930",""],
    ["9*9+13=94 ?","94","OUI"],
    ["En anglais richesse health ?","health",""],
    ["Au Japon on célèbre les fleurs du cerisier ?","Japon ","OUI"],
    ["En anglais de nos jours se dit nowadays ?","nowadays ","OUI"],
    ["Le code départemental de Paris est 75 ?","75","OUI"],
    ["UNIVERSAL STUDIOS sont en Californie","Californie",""],
    ["Date de la 2ème crise pétrolière 1979 ?","1979","OUI"],
    ["L’auteur des Raisins de la colère est George Orwell ?","G. Orwell",""],
    ["C. Perrault a écrit Antigone ?","C. Perrault",""],
    ["Un couard est un peureux ?","peureux","OUI"],
    ["Les émoluments correspondent à une rémunération ?","rémunération","OUI"],
    ["Le code départemental de la Seine maritime est 79 ?","79",""],
    ["9*10=90 ?","90","OUI"],
    ["Recroquevillé est l’antonyme de rabougri ?","rabougri",""],
    ["En anglais très se dit very ?","very","OUI"],
    ["Date du Traité de Rome création de la CEE est 1957 ?","1957","OUI"],
    ["9*10-1=89 ?","89","OUI"],
    ["Les chutes du Niagara sont aux USA et au Canada ?","Canada, Usa","OUI"],
    ["En anglais ensemble eachother ?","eachother",""],
    ["En anglais sagesse kingdom ?","kingdom",""],
    ["Bombes atomiques US Hiroshima Nagasaki  août 1945?","août 1945","OUI"],
    ["Prétentieux est l’antonyme de pédant ? ","pédant",""],
    ["100-15=86 ?","86",""],
    ["Le code départemental de la Haute savoie est 73 ?","73",""],
    ["En anglais Rendez-vous se dit appointment ?","appointment","OUI"],
    ["J. Anouilh a écrit Cendrillon ?","J . Anouilh",""]
  ]

  let list3 = [
    ["La hyène ricane ?","ricane","OUI"],
    ["En anglais donner se dit give ?","give","OUI"],
    ["Le Colisée se trouve en Grèce ?","Grèce",""],
    ["La pyramide de Khéops est en Egypte ?","Egypte","OUI"],
    ["En anglais comment se dit why ?","why",""],
    ["Le sanglier grommelle ?","grommelle","OUI"],
    ["éclater de joie est synonyme d’exulter ?","exulter","OUI"],
    ["l’oisif est un fainéant ?","fainéant","OUI"],
    ["Vélocité veut dire lenteur ?","lenteur",""],
    ["Le code départemental du Val d’oise est 94 ?","94",""],
    ["En anglais commuter est synonyme suburban ?","suburban","OUI"],
    ["Les Attentats du World Trade Center ont eu lieu 11 sep 2000 ?","11 sep 2000",""],
    ["La sauterelle stridule ?","stridule","OUI"],
    ["Un scélérat est un bandit ?","bandit","OUI"],
    ["En anglais thief est synonyme de burglar ? ","Burglar ","OUI"],
    ["Le Taj Mahal se trouve en Inde ?","Inde","OUI"],
    ["En anglais penser se dit thank ?","thank",""],
    ["Le rossignol chante ?","chante","OUI"],
    ["Le code départemental du Val de marne est 95 ?","95",""],
    ["La Chute du mur de Berlin a eu lieu en nov 1990 ?"," Nov 1990",""],
    ["Paroxysme veut dire summum ?","summum","OUI"],
    ["La Statue de la liberté se trouve à New Jersey ?","New Jersey",""],
    ["Le roitelet zinzinule ?","zinzinule","OUI"],
    ["Le code départemental des Hauts de seine est 92 ?","92","OUI"],
    ["La cité interdite se trouve au Japon ?","Japon",""],
    ["La 2ème guerre mondiale a eu lieu de 1939 à 1945 ?"," 1939-1945","OUI"],
    ["La Guerre d’Algérie a eu lieu de 1954 à 1962 ?","1954-1962","OUI"],
    ["Le serpent siffle ?","siffle","OUI"],
    ["Le code départemental de la Seine St Denis est 93 ?","93","OUI"],
    ["Le code départemental de La Réunion est 973 ?","973",""],
    ["La conférence de Bretton Woods a eu lieu en juil 1944 ?","Juill 1944","OUI"],
    ["La grenouille croasse ?","croasse",""],
    ["En anglais gamble est synonyme de bet ? ","bet ","OUI"],
    ["Le zèbre hennit ?","hennit","OUI"],
    ["La crise des subprimes a eu lieu de 2007 à 2009 ?","2007-2009","OUI"],
    ["En anglais interdire se dit forbid ?","forbid","OUI"],
    ["Le Louvre se trouve dans le département 75 ?","75","OUI"],
    ["En anglais venir se dit come ?","come","OUI"],
    ["L’euro a été adopté en 2002 ?","2002","OUI"],
    ["Bavard est synonyme de loquace ?","loquace","OUI"],
    ["Le code départemental de la Martinique est 971 ?","971",""],
    ["En anglais geler se dit freeze ?","freeze","OUI"],
    ["Le code départemental de la Guadeloupe est 972 ?","972",""],
    ["Big Ben se trouve à New York ?","New York",""],
    ["Le Parc des Galapagos se trouve en Equateur ?","Equateur","OUI"],
    ["En anglais citer se dit quote ?","quote","OUI"],
    ["La vache meugle ?","meugle","OUI"],
    ["Le code départemental de l’Essonne est 91 ?","91","OUI"],
    ["En anglais steal est synonyme de rob ?","rob","OUI"],
    ["En anglais biscuit est synonyme de cookie ?","cookie","OUI"],
    ["L’ Armistice a été signé le 11 nov 1918 ?","11 nov 1918","OUI"],
    ["En anglais cautious est synonyme de careful ? ","careful","OUI"],
    ["Une anicroche est une difficulté ?","difficulté","OUI"],
    ["Le code départemental duTerritoire de belfort est 90 ?","90","OUI"],
    ["Le corbeau coasse ?","coasse",""],
    ["Un capharnaüm est un bazar ?","bazar","OUI"],
    ["Le Carnaval de Rio se déroule au Brésil ?","Brésil","OUI"],
    ["La 1ère guerre mondiale a eu lieu de 1912-1918 ?","1912-1918 ",""],
    ["Le code départemental de la Guyane est 974 ?","974",""],
    ["Le grand Canyon se trouve en Arizona ?","Arizona","OUI"],
    ["En anglais pourquoi se dit who ?","who",""],
    ["Acquiescer veut dire accepter ?","accepter","OUI"],
    ["Versatile veut dire changeant ?","changeant","OUI"],
    ["En anglais dwell est synonyme de live ?","live","OUI"]
  ]

  let list4 = [
    ["Gabegie est contraire de gaspillage ?","Gaspillage",""],
    ["En anglais become veut dire devenir ?","devenir","OUI"],
    ["En anglais walk veut dire marcher ?","marcher","OUI"],
    ["On dit un atome ?","atome","OUI"],
    ["En anglais apologize veut dire apologie ? ","apologie",""],
    ["144/12=12 ?","12","OUI"],
    ["196/7=28 ?","28","OUI"],
    ["On dit un antipode ?","antipode","OUI"],
    ["En anglais who veut dire où ?","où",""],
    ["135/9=15 ?","15","OUI"],
    ["888/111=9 ?","9",""],
    ["Corroborer est synonyme de crédibiliser ?","Crédibiliser","OUI"],
    ["Incurie est synonyme de négligence ?","Négligence","OUI"],
    ["En anglais sentence veut dire sentence ? ","sentence",""],
    ["196/14=14 ?","14","OUI"],
    ["287/7=41 ?","41","OUI"],
    ["résilience est synonyme de résistance ?","résistance","OUI"],
    ["Fustiger est synonyme de réprimander ?","Réprimander","OUI"],
    ["On dit une alluvion ?","alluvion","OUI"],
    ["On dit une encaustique","encaustique","OUI"],
    ["En anglais then veut dire alors ?","alors","OUI"],
    ["En anglais pride veut dire fier ?","fier","OUI"],
    ["Litanie est synonyme d’énumération ?","Enumération","OUI"],
    ["On dit une auspice ","auspice",""],
    ["En anglais wear veut dire où ?","où",""],
    ["En anglais be veut dire être ?","être","OUI"],
    ["415/5=100?","100",""],
    ["ostentatoire est synonyme d’orgueilleux ?","Orgueilleux","OUI"],
    ["Abyssal est synonyme de considérable ?","Considérable","OUI"],
    ["Hérésie est synonyme d’erreur ?","Erreur","OUI"],
    ["On dit un aérogare ?","aérogare",""],
    ["456/8=57 ?","57","OUI"],
    ["On dit une ébène ?","ébène","OUI"],
    ["340/4=85 ?","85","OUI"],
    ["Risée est synonyme de moquerie ?","Moquerie","OUI"],
    ["Offusquer est contraire d’offenser ?","Offenser",""],
    ["On dit un éloge ?","éloge","OUI"],
    ["Florilège est synonyme de choix ?","Choix","OUI"],
    ["En anglais word veut dire monde ?","monde",""],
    ["512/8=64 ?","64","OUI"],
    ["Hégémonie est contraire de suprématie ?","Suprématie",""],
    ["En anglais instead of veut dire au lieu de ?","au lieu de","OUI"],
    ["Anathème est contraire de condamnation ?","Condamnation",""],
    ["222/6=37 ?","37","OUI"],
    ["Pléonasme est le contraire de répétition ?","Répétition",""],
    ["En anglais cope with veut dire faire face ? ","faire face","OUI"],
    ["212/4=75 ?","75",""],
    ["En anglais why veut dire pourquoi ? ","pourquoi","OUI"],
    ["432/6=72 ?","72","OUI"],
    ["282/6=47 ?","47","OUI"],
    ["Dubitatif est synonyme de méfiant ?","Méfiant","OUI"],
    ["378/7=54 ?","54","OUI"],
    ["Eminence est synonyme d ‘infériorité ?","infériorité",""],
    ["Déliquescence est contraire de détérioration ?","Détérioration",""],
    ["En anglais who veut dire qui ?","qui","OUI"],
    ["Sublimer est synonyme de magnifier ?","Magnifier","OUI"],
    ["Euphémisme est synonyme de périphrase ?","Périphrase","OUI"],
    ["200/8=25 ?","25","OUI"],
    ["On dit une arcane ","arcane",""],
    ["On dit un anicroche ?","anicroche",""],
    ["322/7=46 ?","46","OUI"],
    ["365/5=73 ?","73","OUI"],
    ["385/5=77 ?","77","OUI"],
    ["200/5=50 ?","50",""]
  ]

  let list5 = [
    ["On dit une épitaphe ?","épitaphe","OUI"],
    ["En anglais acheter s’écrit by ?","by",""],
    ["On dit une oriflamme ?","oriflamme","OUI"],
    ["En anglais trouver se dit find ?","find","OUI"],
    ["On dit un ustensile ? ","ustensile","OUI"],
    ["En anglais coûter se dit cost ?","cost","OUI"],
    ["240/5=48 ?","48","OUI"],
    ["On dit une organe ? ","organe",""],
    ["305/5=61 ?","61","OUI"],
    ["392/8=100 ?","100",""],
    ["114/6=19 ?","19","OUI"],
    ["On dit un opercule","opercule","OUI"],
    ["En anglais porter se dit wear ?","wear","OUI"],
    ["Un pourceau grognonne ?","grognonne","OUI"],
    ["On dit un équerre","équerre",""],
    ["On dit une ovule ? ","ovule",""],
    ["En anglais connaître, savoir s’écrit now ?","now",""],
    ["224/7=32 ?","32","OUI"],
    ["On dit une stalactite ?","stalactite","OUI"],
    ["En anglais apporter se dit bring ?","bring","OUI"],
    ["445/5=89 ?","89","OUI"],
    ["264/8=33 ?","33","OUI"],
    ["On dit une équinoxe ?","équinoxe",""],
    ["En anglais boire se dit drink ?","drink","OUI"],
    ["Un rhinocéros barète ?","barète","OUI"],
    ["On dit un hiéroglyphe ?","hiéroglyphe","OUI"],
    ["On dit un réglisse ?","réglisse",""],
    ["252/7=36 ?","36","OUI"],
    ["207/3=69 ?","69","OUI"],
    ["En anglais oublier se dit forgive ?","forgive",""],
    ["la poule raille","raille",""],
    ["324/18=18 ?","18","OUI"],
    ["En anglais construire se build ?","build","OUI"],
    ["En anglais faire se dit do ?","do","OUI"],
    ["En anglais recevoir, obtenir se dit get ?","get","OUI"],
    ["On dit une omoplate ?","omoplate","OUI"],
    ["777/111=10 ?","10",""],
    ["On dit une autographe ? ","autographe",""],
    ["En anglais apprendre se dit learn ?","learn","OUI"],
    ["On dit une épiderme ? ","épiderme",""],
    ["On dit une intervalle ","intervalle",""],
    ["289/17=17 ?","17","OUI"],
    ["738/9=82 ?","82","OUI"],
    ["306/9=50 ?","50",""],
    ["On dit un météorite ?","météorite",""],
    ["On dit un prémisse ?","prémisse",""],
    ["En anglais manger s’écrit it ?","it",""],
    ["990-979=20 ?","20",""],
    ["En anglais laisser, quitter s’écrit live ?","live",""],
    ["Un goéland caquette ?","caquette",""],
    ["490/7=90 ?","90",""],
    ["En anglais aller se dit go ?","go","OUI"],
    ["On dit un antre ? ","antre","OUI"],
    ["252/3=84 ?","84","OUI"],
    ["441/7=63 ?","63","OUI"],
    ["Un renard piaule ?","piaule",""],
    ["On dit un orifice ? ","orifice","OUI"],
    ["Un rat glapit ?","glapit",""],
    ["195/5=39 ?","39","OUI"],
    ["On dit un épilogue ? ","épilogue","OUI"],
    ["En anglais comprendre se dit stand ?","stand",""],
    ["312/4=78 ?","78","OUI"],
    ["En anglais commencer se dit begin ?","begin","OUI"],
    ["En anglais conduire se dit drive ?","drive","OUI"]
  ]

  let list6 = [
    ["En anglais  arrière se dit back ?","back","OUI"],
    ["Dialogue est contraire d’aparté ?","aparté","OUI"],
    ["Le Mont Pelée se trouve en France ?","France","OUI"],
    ["Le mont Kailash se trouve au Tibet ?","Tibet","OUI"],
    ["En anglais en bas se dit down ?","down ","OUI"],
    ["232/8=29 ?","29","OUI"],
    ["En anglais toujours se dit always ?","always","OUI"],
    ["En anglais  pendant se dit during ?","during","OUI"],
    ["Dépensier est synonyme d’avare ?","avare",""],
    ["395/5=79 ?","79","OUI"],
    ["En anglais encore se dit against ?","against",""],
    ["Coïncidence est contraire de divergence ?","divergence","OUI"],
    ["Le volcan Irazu se trouve en Colombie ?","Colombie",""],
    ["568/8=71 ?","71","OUI"],
    ["En anglais comme s’écrit has ?","has ",""],
    ["En anglais mais se dit but ?","but ","OUI"],
    ["En anglais  même se dit even ?","even","OUI"],
    ["Indulgence est contraire de sévérité ?","sévérité","OUI"],
    ["207/9=23 ?","23","OUI"],
    ["En anglais tout se dit all ?","all","OUI"],
    ["Occidental est contraire d’oriental ?","oriental","OUI"],
    ["En anglais entre se dit between ?","between","OUI"],
    ["En anglais pour s’écrit four ?","four",""],
    ["Le Half Dome se trouve en Australie ?","Australie ",""],
    ["En anglais aussi se dit although ?","although",""],
    ["La montagne la Main de Fatma se trouve au Mali ?","Mali","OUI"],
    ["750/15=100 ?","100",""],
    ["l’Eyjahjoll se trouve en Irlande ?","Irlande",""],
    ["126/6=21 ?","21","OUI"],
    ["592/8=74 ?","74","OUI"],
    ["En anglais avant se dit before ?","before ",""],
    ["516/6=86 ?","86","OUI"],
    ["Méridional est contraire de septentrional ?","septentrional","OUI"],
    ["990-980=30 ?","30",""],
    ["Le Kilimandjaro se trouve au Congo?","Congo",""],
    ["144/9=16 ?","16","OUI"],
    ["Inopportun est contraire de propice ?","propice","OUI"],
    ["372/6=62 ?","62","OUI"],
    ["204/4=51 ?","51","OUI"],
    ["232/4=58 ?","58","OUI"],
    ["En anglais  loin se dit far ?","far","OUI"],
    ["486/6=81 ?","81","OUI"],
    ["344/8=43 ?","43","OUI"],
    ["En anglais  il y a, depuis se dit ago ?","ago","OUI"],
    ["En anglais et s’écrit hand ?","hand ?",""],
    ["En anglais tous les deux se dit both ?","both","OUI"],
    ["En anglais assez se dit enough ?","enough","OUI"],
    ["Opprobre est le contraire de gloire ?","gloire","OUI"],
    ["En anglais  à, de, en train de se dit at ?","at","OUI"],
    ["En anglais par, de s’écrit buy ?","buy ",""],
    ["Gloire est synonyme de déclin ?","déclin",""],
    ["Le Stromboli se trouve en Sicile ?","Sicile","OUI"],
    ["280/8=28 ?","28",""],
    ["En anglais après se dit after ?","after ","OUI"],
    ["En anglais  avant se dit behind ?","behind",""],
    ["Goulu est contraire de frugal ?","frugal","OUI"],
    ["Le Vésuve se trouve à Naples ?","Naples","OUI"],
    ["En anglais contre se dit again ?","again",""],
    ["Pérennité est synonyme de brièveté ?","brièveté",""],
    ["228/6=38 ?","38","OUI"],
    ["405/9=45 ?","45","OUI"],
    ["594/9=66 ?","66","OUI"],
    ["Le mont Fuji se trouve au Japon ?","Japon","OUI"],
    ["800/40=40","40",""]
  ]

  let list7 = [
    ["198/11=18 ?","18","OUI"],
    ["En anglais une fois se dit once ?","once","OUI"],
    ["On dit un opprobre ?","opprobre","OUI"],
    ["En anglais dehors se dit out ?","out ","OUI"],
    ["225/5=50 ?","50",""],
    ["En anglais  souvent se dit often ?","often ","OUI"],
    ["300/30=30 ?","30",""],
    ["264/12=22 ?","22","OUI"],
    ["En anglais  soi se dit self ?","self ","OUI"],
    ["On dit un épithète ?","épithète",""],
    ["On dit un urticaire","urticaire",""],
    ["225/3=100 ?","100",""],
    ["On dit une hémorroïde ?","hémorroïde","OUI"],
    ["252/4=63 ?","63","OUI"],
    ["50*2+8=108 ?","108","OUI"],
    ["246/11=24 ?","24","OUI"],
    ["En anglais ou, ou bien se dit or ?","or ","OUI"],
    ["Molière a écrit Candide ?","Molière",""],
    ["Frénésie est contraire de calme ?","calme","OUI"],
    ["En anglais  près se dit near ?","near ","OUI"],
    ["En anglais de s’écrit off ?","off",""],
    ["C. Baudelaire a écrit Les Fleurs du mal ?"," C. Baudelaire","OUI"],
    ["On dit un oasis ?","oasis",""],
    ["216/3=72 ?","72","OUI"],
    ["L’Etranger a été écrit par Camus ?","Camus","OUI"],
    ["On dit un hectare ?","hectare","OUI"],
    ["243-162=100 ?","100",""],
    ["En anglais peut-être se dit perhaps ?","perhaps","OUI"],
    ["En anglais maintenant s’écrit know ?","know",""],
    ["Le Petit prince a été écrit par St Exupéry ?"," St-Exupéry","OUI"],
    ["Circonspect est contraire d’imprudent ?","imprudent","OUI"],
    ["La capitale de la SUISSE est Genève ?","Genève",""],
    ["204/3=68 ?","68","OUI"],
    ["En anglais sur, dans, par se dit on ?","on","OUI"],
    ["372/12=31 ?","31","OUI"],
    ["276/12=23 ?","23","OUI"],
    ["En anglais beaucoup se dit much ?","much ","OUI"],
    ["201/3=67 ?","67","OUI"],
    ["En anglais jamais s’écrit neither ?","Neither ",""],
    ["L’Avare a été écrit par Voltaire ?","Voltaire",""],
    ["On dit un orbite ?","orbite",""],
    ["La capitale du MAROC est Rabat ?","Rabat","OUI"],
    ["255/3=85 ?","85","OUI"],
    ["En anglais  rien se dit nothing ?","nothing","OUI"],
    ["La capitale de la Nouvelle-Zélande est Wellington ?","Wellington","OUI"],
    ["375-270=100 ?","100",""],
    ["295-240=67 ?","67",""],
    ["En anglais éteint, absent s’écrit of ?","of",""],
    ["En anglais seulement se dit only ?","only","OUI"],
    ["Notre-Dame de Paris a été écrit par Zola ?","Zola",""],
    ["On dit un poulpe ?","poulpe","OUI"],
    ["Synonyme est l’antonyme de contraire ?","contraire","OUI"],
    ["En anglais le plus se dit most ?","most ","OUI"],
    ["En anglais sur, plus de s’écrit other ? ","other ",""],
    ["154/2=80 ?","80",""],
    ["En anglais depuis se dit since ?","since","OUI"],
    ["On dit une hydre ?","hydre","OUI"],
    ["On dit une entracte ? ","entracte",""],
    ["215/5=43 ?","43","OUI"],
    ["174/3=58 ?","58","OUI"],
    ["En anglais non, marque de négation se dit no ?","no","OUI"],
    ["En anglais oui se dit yes ?","yes","OUI"],
    ["Germinal a été écrit par Victor Hugo ?","V. Hugo",""],
    ["Pieux est contraire de païen ?","païen","OUI"]
  ]

  let list8 = [
    ["194/2=100 ?","100",""],
    ["J ; de la Fontaine a écrit Le vieil homme et la mer ?","J. de la Fontaine",""],
    ["90/15=10 ?","10",""],
    ["En anglais pourquoi se dit why ?","why","OUI"],
    ["Dépensier est synonyme d’avare ?","avare",""],
    ["376/4=94 ?","94","OUI"],
    ["En anglais entier se dit hole ? ","hole",""],
    ["Haranguer est contraire de complimenter ?","complimenter","OUI"],
    ["222/3=74","74","OUI"],
    ["264/3=88 ?","88","OUI"],
    ["En anglais quel, quelle se dit which ?","which","OUI"],
    ["En anglais  ici s’écrit hear ?","hear",""],
    ["297/3=99 ?","99","OUI"],
    ["360-306=70 ?","70",""],
    ["En anglais comment se dit how ?","how ","OUI"],
    ["La Seine se trouve en France ?","France","OUI"],
    ["500-471=50 ?","50",""],
    ["Le lac de Côme se trouve en Suisse ?","Suisse",""],
    ["300-222=90 ?","90",""],
    ["En anglais  tandis que se dit while ?","while ","OUI"],
    ["En anglais juste se dit  just ?","just","OUI"],
    ["Véloce est synonyme de lent ?","lent",""],
    ["Alourdir est l’antonyme d’alléger ?","alléger","OUI"],
    ["85/17=5 ?","5","OUI"],
    ["262-160=102 ?","102","OUI"],
    ["En anglais dans se dit in ?","in ","OUI"],
    ["Rostand a écrit Cyrano de Bergerac ?","Rostand","OUI"],
    ["360/12=90 ?","90",""],
    ["En anglais quoi se dit what ?","what","OUI"],
    ["En anglais  principal se dit main ? ","main  ","OUI"],
    ["Insidieux est contraire de franc ?","franc","OUI"],
    ["Pérennité est l’antonyme de brièveté ?","brièveté","OUI"],
    ["Le fleuve Orange se trouve au Togo ?","Togo",""],
    ["En anglais quand se dit when ?","when","OUI"],
    ["Le lac Léman se trouve en Autriche ? ","Autriche",""],
    ["204/4=51 ?","51","OUI"],
    ["Flaubert a écrit Le tour du monde en 80 jours ?","Flaubert",""],
    ["Les lacs de Plitvice se trouve en Croatie ? ","Croatie","OUI"],
    ["En anglais beaucoup se dit many ?","many ","OUI"],
    ["84/12=10 ?","10",""],
    ["Jules Verne a écrit Madame Bovary ?","Jules Verne",""],
    ["Incommensurable est contraire de mesurable ?","mesurable","OUI"],
    ["275/11=25 ?","25","OUI"],
    ["384/4=96 ?","96","OUI"],
    ["292/4=73 ?","73","OUI"],
    ["En anglais peu se dit few ?","few","OUI"],
    ["En anglais  où s’écrit wear ?","wear ",""],
    ["En anglais de, a partir de se dit from ?","from ","OUI"],
    ["En anglais plus se dit more ?","more","OUI"],
    ["Hemingway a écrit Le chêne et le roseau ?","Hemingway",""],
    ["Couard  est synonyme de courageux ?","courageux",""],
    ["La Ruhr se trouve en Italie ?","Italie",""],
    ["La Tamise se trouve en Russie ?","Russie",""],
    ["252/12=21 ?","21","OUI"],
    ["792-699=100 ?","100",""],
    ["En anglais  beaucoup se dit lot ?","lot  ","OUI"],
    ["En anglais qui se dit who ?","who ","OUI"],
    ["Stendhal a écrit Le rouge et le noir ?","Stendhal","OUI"],
    ["Le fleuve Ogoué se trouve au Gabon ?","Gabon","OUI"],
    ["483-380=200 ?","200",""],
    ["Versatile est synonyme de constant ?","constant",""],
    ["La Volga se trouve en Allemagne ?","Allemagne",""],
    ["En anglais rapide se dit quick ? ","quick ","OUI"],
    ["En anglais si se dit if ?","if  ","OUI"]
  ]

  let list9 = [
    ["890-799=91 ?","91","OUI"],
    ["Le zèbre hennit ?","hennit","OUI"],
    ["En anglais par se dit through ?","through","OUI"],
    ["Le rossignol bavarde ?","bavarde",""],
    ["96/12=10 ?","10",""],
    ["Le lac Rukwa se trouve en Tanzanie ?","Tanzanie","OUI"],
    ["258/3=86 ?","86","OUI"],
    ["8*10+27=107 ?","107","OUI"],
    ["141/3=47 ?","47","OUI"],
    ["En anglais  en haut se dit up ?","up ","OUI"],
    ["356/4=120 ?","120",""],
    ["En anglais là se dit there ?","there","OUI"],
    ["En anglais  encore se dit yet ?","yet ","OUI"],
    ["La Laguna Colorada se trouve en Colombie ?","Colombie",""],
    ["En anglais aussi s’écrit to ?","to",""],
    ["9*10+16=150 ?","150",""],
    ["Le lion rugit ?","rugit","OUI"],
    ["gabegie est synonyme d’économie ?","économie",""],
    ["343-261=82 ?","82","OUI"],
    ["169/13=13 ?","13","OUI"],
    ["En anglais tellement, tel se dit such ?","such ","OUI"],
    ["La grenouille croasse ?","croasse",""],
    ["Silencieux est synonyme de volubile ?","volubile",""],
    ["Le lac Moraine se trouve au Canada ?","Canada","OUI"],
    ["165/11=15 ?","15","OUI"],
    ["En anglais  que se dit than ?","than","OUI"],
    ["En anglais  jusqu’à se dit until ?","until ","OUI"],
    ["192/3=64 ?","64","OUI"],
    ["En anglais bien que s’écrit thought ?","thought",""],
    ["La pintade criaille ?","criaille","OUI"],
    ["Le lac Erié se trouve en Suisse ?","Suisse",""],
    ["En anglais ensemble se dit together ?","together ","OUI"],
    ["En anglais vers se dit toward ?","toward ","OUI"],
    ["En anglais  très se dit very ?","very","OUI"],
    ["Le pigeon caracoule ?","caracoule","OUI"],
    ["900/15=60 ?","60","OUI"],
    ["294/3=100 ?","100",""],
    ["Le roitelet zinzinule ?","zinzinule","OUI"],
    ["Le lac de Gadi Sagar se trouve en Inde ?","Inde","OUI"],
    ["111/3=37 ?","37","OUI"],
    ["En anglais  avec se dit with ?","with  ","OUI"],
    ["Le sanglier grommelle ?","grommelle","OUI"],
    ["En anglais bientôt se dit soon ?","soon","OUI"],
    ["Le lac Tana se trouve en Ethiopie ?","Ethiopie","OUI"],
    ["Le lac Yamdrok Tso se trouve en Chine","Chine",""],
    ["8*8+45=109 ?","109","OUI"],
    ["156/3=60 ?","60",""],
    ["En anglais oui se dit yes ?","yes","OUI"],
    ["360/4=150 ?","150",""],
    ["En anglais encore s’écrit steal ?","steal",""],
    ["En anglais  sous se dit under ?","under ","OUI"],
    ["La pie chante ?","chante",""],
    ["Audacieux est synonyme de timoré ?","timoré",""],
    ["401-322=79 ?","79","OUI"],
    ["Le lac Huanglong se trouve au Tibet ?","Tibet",""],
    ["En anglais  puis se dit then ?","then","OUI"],
    ["Excepter est le contraire d’inclure ?","inclure","OUI"],
    ["286/11=26 ?","26","OUI"],
    ["Goguenard est contraire de sérieux ?","sérieux","OUI"],
    ["560-460=200 ?","200",""],
    ["En anglais donc s’écrit sow ?","sow ",""],
    ["En anglais à s’écrit too ?","too",""],
    ["La vache bêle ?","bêle",""],
    ["La laguna Torre se trouve en Argentine ?","Argentine","OUI"]
  ]

  let list10 = [
    ["156/13=12 ?","12","OUI"],
    ["En anglais forbid est contraire de allow ?","allow ","OUI"],
    ["La femelle du cheval est la jument ?","jument","OUI"],
    ["La femelle du sanglier est la laie ?","laie","OUI"],
    ["186/3=62 ?","62","OUI"],
    ["Inopportun est contraire de propice ?","propice","OUI"],
    ["265/5=53 ?","53","OUI"],
    ["En anglais several est contraire de one ?","one","OUI"],
    ["Indulgence est synonyme de sévérité ?","sévérité",""],
    ["Réticence est contraire d’assurance ?","assurance","OUI"],
    ["En anglais tasty est synonyme de bland ?","bland",""],
    ["En anglais well-done est contraire de raw ?","raw","OUI"],
    ["La femelle du merle est la merlette ?","merlette","OUI"],
    ["276/6=46 ?","46","OUI"],
    ["En anglais spare est synonyme de spend ?","spend",""],
    ["La femelle du cerf est la biche ?","biche","OUI"],
    ["La femelle du dindon est la dinde ?","dinde","OUI"],
    ["276/4=69 ?","69","OUI"],
    ["En anglais cold est synonyme de hot ?","hot",""],
    ["Dialogue dialogue est contraire d’aparté ?","aparté","OUI"],
    ["360–301=60 ?","60",""],
    ["192/4=48 ?","48","OUI"],
    ["475/5=95 ?","95","OUI"],
    ["En anglais expensive est contraire de cheap ?","cheap","OUI"],
    ["Docile est synonyme de dur ?","dur",""],
    ["La femelle du chameau est la chamelle ?","chamelle","OUI"],
    ["La femelle du jars est oie ?","oie","OUI"],
    ["332/4=83 ?","83","OUI"],
    ["En anglais good est contraire de bad ?","bad","OUI"],
    ["La femelle du porc est la truite ?","truite",""],
    ["La femelle du loup est la louve ?","louve","OUI"],
    ["550-470=100 ?","100",""],
    ["En anglais cute est synonyme de ugly ?","ugly",""],
    ["En anglais happy contraire de sad ?","sad","OUI"],
    ["280/5=70 ?","70",""],
    ["En anglais white contraire de black ?","black","OUI"],
    ["Rugueux est synonyme de lisse ?","lisse",""],
    ["En anglais youngster est synonyme d’elders","elders",""],
    ["Audacieux est contraire de timoré ?","timoré","OUI"],
    ["216/6=36 ?","36","OUI"],
    ["200-99=110 ?","110",""],
    ["En anglais noisy est contraire de quiet ?","quiet","OUI"],
    ["La femelle du singe est la guenon ?","guenon","OUI"],
    ["220/11=30 ?","30",""],
    ["324/12=27 ?","27","OUI"],
    ["La femelle du mouton est la brebis ?","brebis","OUI"],
    ["348/4=87 ?","87","OUI"],
    ["En anglais poor contraire de rich ?","rich","OUI"],
    ["Gloire est contraire de déclin ?","déclin","OUI"],
    ["Éphémère est synonyme d’éternel ?","éternel",""],
    ["Antonyme est contraire de synonyme ?","synonyme","OUI"],
    ["La femelle du lièvre est la hase ?","hase","OUI"],
    ["304/4=76 ?","76","OUI"],
    ["152/4=200 ?","200",""],
    ["En anglais stupid est contraire de clever ?","clever","OUI"],
    ["En anglais tall est synonyme de short ? ","Short ",""],
    ["En anglais close est contraire de open ?","open","OUI"],
    ["Silencieux est synonyme de volubile ?","volubile",""],
    ["En anglais slow est contraire de fast ?","fast","OUI"],
    ["En anglais day est contraire de night ?","night","OUI"],
    ["117/13=9 ?","9","OUI"],
    ["1000-908=120 ?","120",""],
    ["En anglais slim est synonyme de large ?","large",""],
    ["La femelle du chevreuil est la chevrette ?","chevrette","OUI"]
  ]

    
  function sendList(level) {
    if (level ===1) {return list1}
    if (level ===2) {return list2}
    if (level ===3) {return list3}
    if (level ===4) {return list4}
    if (level ===5) {return list5}
    if (level ===6) {return list6}
    if (level ===7) {return list7}
    if (level ===8) {return list8}
    if (level ===9) {return list9}
    if (level ===10) {return list10}

}

export default sendList